### ISSUE TITLE
`npm run dev` does not work

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/OntoPad#16]
According to `https://github.com/AKSW/OntoPad/blob/master/README.md`, I can run OntoPad using `npm run dev`, however that results in `npm ERR! missing script: dev`.

**Comment by KonradHoeffner** [comment]
The scripts in `package.json` indeed don't contain `dev`:

```
  "scripts": {  
    "serve": "vue-cli-service serve",  
    "build": "vue-cli-service build --modern",
    "lint": "vue-cli-service lint",
    "test": "jest"
  },

```

**Comment by white-gecko** [comment]
It is `npm run serve` sorry for that.
