### ISSUE TITLE
How to serve output of npm build?

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/OntoPad#17]
As `npm run dev` did not work for me. I successfully build the project using `npm run build`, however I cannot figure out how to start it then.
I tried opening `dist/index.html` on Firefox Developer 87.0b8 and Chromium 89.0.4289.82 even with the CORS addon activated but there is just a white screen.

The console shows the error message:

```
Loading failed for the module with source “file:///js/chunk-vendors.63bccdb5.js”. index.html:1:1
Loading failed for the module with source “file:///js/app.22d9930c.js”. index.html:1:1
```

I also deployed it on a local webserver using `$ python -m http.server .` but that failed as well.

**Comment by white-gecko** [comment]
Thank you for the question. You should serve it with a local HTTP server, like `python3 -m http.server 8080` because webpack builds absolute paths. Also that would not do the whole trick, as you still need a config, which is now explained in the README.
