### ISSUE TITLE
How to create SHACL constraints and enforce them on new data?

### ISSUE THREAD

**Issue by Timonsc** [AKSW/OntoPad#21]
Hi,

I'm interested in the project and was curious if it's possible to both define shacl constraints and enforce them on newly added data. Is this possible? I don't completely understand where the shapes end up and what they do after creating them in the vocabulary tab.

Am I missing something? 

Kr,
Timon

**Comment by white-gecko** [comment]
The shapes are stored in the underlying triple store, if you click on the top right save button.
Currently the data creation component has not the necessary shacl support, but it is under development: https://github.com/simeonackermann/RDForm/issues/18

**Comment by Timonsc** [comment]
Interesting! And is the goal of this shacl support to also validate the data that is ingested via the editor by those shacl rules before committing?

**Comment by white-gecko** [comment]
at least it is the goal to create a form based on the shacl shape to guide people in creating valid data.

**Comment by Timonsc** [comment]
Okay, thank.
