### ISSUE TITLE
Broken link to the demo

### ISSUE THREAD

**Issue by CaptSolo** [AKSW/OntoPad#23]
The link to the demo of OntoPad is broken (returns 404 Not Found error):

https://ontopad.aksw.org/

**Comment by white-gecko** [comment]
The demo is now available again. It now runs completely in the browser, thanks to comunica. The vocabulary/SHACL part is not restored yet.

**Comment by white-gecko** [comment]
The new code is under the `next` branch, will be merged to master or main eventually.
