### ISSUE TITLE
Tutorial/video with at least one example

### ISSUE THREAD

**Issue by firmao** [AKSW/OntoPad#4]
The creation of a manual/tutorial/video explaining at least one example working with the whole application.

**Comment by RicardoUsbeck** [comment]
and screenshots please :)

**Comment by white-gecko** [comment]
I have added intro.js (dfeb40bf81268da1ae21263193d76a732d03261f) for now so you can get a tour on the online demo http://demo.ontopad.aksw.org/#/voc

**Comment by white-gecko** [comment]
There are screenshot in the paper https://svn.aksw.org/papers/2020/iswc_voila_ontopad/public.pdf
